### ISSUE TITLE
Is the reading host env function workable with istio-proxy?

### ISSUE THREAD

**Issue by linzg2002** [proxy-wasm/spec#30]
@mathetake I am very interested on this reading host env feature. So I just reviewed all issues and PR around this topic. But still not very clear about how to use it in real case. Could you give some tips? Such as how to config it in envoy.yaml and how to write the code in the wasm filter in C++?
I actually had tried like this:
in istio envoyfilter.yaml
```
config:
  root_id: my_root_id
  vm_config:
    code:
      local:
        filename: /var/local/lib/wasm-filters/example-filter.wasm
    runtime: envoy.wasm.runtime.v8
    vm_id: "my_vm_id"
    environment_variables: ["HOME"]
```
in my wasm-filter.cc
```
    this->theHome = std::getenv("HOME");
```
Unluckily,  I got nothing output. So anywrong I did on this? Bwt, is the function support by istio-envoy? and which should the istio version to be at least? Looking forward for your help, thanks in advance.
